import axios from 'axios'
import React from 'react'
import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [ip, setIp] = React.useState('')
  const [port, setPort] = React.useState('')
  const handleOnPrevSlide = () => {
    axios
      .get(`http://${ip}:${port}/v1/presentation/focused/previous/trigger`)
      .then()
  }

  const handleOnNextSlide = () => {
    axios
      .get(`http://${ip}:${port}/v1/presentation/focused/next/trigger`)
      .then()
  }

  const onIpChanged = (e: any) => {
    setIp(e.target.value)
  }

  const onPortChanged = (e: any) => {
    setPort(e.target.value)
  }

  return (
    <>
      <Head>
        <title>ProPresenter Remote</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.inputs}>
          <label>
            <div className={styles.label}>IP:</div>{' '}
            <input
              className={styles.input}
              type={'text'}
              placeholder={'xx.xx.xx.xx'}
              onChange={onIpChanged}
            />
          </label>
          <label>
            <div className={styles.label}>Port:</div>{' '}
            <input
              className={styles.input}
              type={'text'}
              placeholder={'xxxx'}
              onChange={onPortChanged}
            />
          </label>
        </div>

        <div className={styles.description}>
          <p>Get started by entering the ip & port for the ProPresenter</p>
        </div>

        <div className={styles.flex}>
          <div onClick={handleOnPrevSlide} className={styles.card}>
            <h2 className={inter.className}>
              <span>&lt;-</span>
            </h2>
          </div>
          <div onClick={handleOnNextSlide} className={styles.card}>
            <h2 className={inter.className}>
              <span>-&gt;</span>
            </h2>
          </div>
        </div>
      </main>
    </>
  )
}
